### ISSUE TITLE
iceoryx v2.0.5 support

### ISSUE THREAD

**Issue by HarelAshwal** [High-tech-digital-modules/iceoryx-nodejs#3]
LK"I

Hello,

I'm currently using iceoryx-nodejs with iceoryx v2.0.2. 
However, when attempting to use it with iceoryx v2.0.5, I encountered compatibility issues and it failed to work.

Are there any plans to update iceoryx-nodejs to make it compatible with iceoryx v2.0.5? 
Below is the error log for reference:

```
root@84bb9d6ba1df:/home/test# npm install iceoryx-nodejs

> iceoryx-nodejs@0.0.2 install /home/test/node_modules/iceoryx-nodejs
> node-gyp rebuild

make: Entering directory '/home/test/node_modules/iceoryx-nodejs/build'
  CXX(target) Release/obj.target/iceoryx/src/iceoryx.o
In file included from ../src/iceoryx.cc:2:
../include/iceoryx_subscriber.h:4:10: fatal error: iceoryx_hoofs/cxx/optional.hpp: No such file or directory
    4 | #include "iceoryx_hoofs/cxx/optional.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [iceoryx.target.mk:115: Release/obj.target/iceoryx/src/iceoryx.o] Error 1
make: Leaving directory '/home/test/node_modules/iceoryx-nodejs/build'

```

**Comment by HarelAshwal** [comment]
Sorry my bad, it works with v2.0.5
